languageCode = "zh-cn"
languageName = "简体中文"
weight = 9
title = "Ivo's Inkwell"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.png"
  description = "一个强大、轻量级的 Hugo 主题。"

[params.author]
  name = "Ivo"
  image = "img/avatar.png"
  headline = "Don't let the noise of others' opinions drown out your own inner voice."
  bio = "Don't let the noise of others' opinions drown out your own inner voice."
  links = [
    #{ x-twitter = "https://twitter.com/burufugu" },
    #{ github = "https://github.com/lylechen-dev" },
  ]
